### PR TITLE
Dotnet

### PR DESCRIPTION
**Pull request by amidgol**

### CODE REVIEW

**Comment by amidgol** [comment]
Three projects have been added as case studies. Also another project under `em` directory has been added which contains an embedded driver for one of the case studies (`Library` project), but it's still in progress and has some problems to be solved

**Comment by arcuri82** [comment]
Hi @amidgol !
  thx ;)  Couple of things:
- I updated the README. Can you fill there the missing info? (see the TODO)
- the `em` projects have hard-coded links to the location of dotnet-client. This latter should be published as NuGet package, which can then be installed locally. See https://stackoverflow.com/questions/57791059/how-to-nuget-install-in-nuget-folder-when-compiling-locally 
- also will need to update the OutputFormat once that is done in dotnet-client

**Comment by amidgol** [comment]
Hi @arcuri82 

- Case-studies of dotnet added to the README.md
- I added a nuget config file containing a local nuget source which is a folder inside EvoMaster root. Libraries of the driver are being packed on build and published to that local nuget source. Now the library inside e2e has a reference to the nuget package of Controller
- A value for C# added to the OutputFormat

Best regards

**Comment by arcuri82** [comment]
thx Amid!
thanks for checking the Nuget handling. But has it been fixed here as well? eg, see relative paths in `Library.csproj`, `Menu.csproj` and `SampleProject.csproj`

**Comment by arcuri82** [comment]
thx! see my comment in the other rep, regarding package naming. after that is done, we can merge

**Pull request merged**
