### PR TITLE
PR to fix develop branch

### PR DESCRIPTION
**Pull request by jgaleotti**
The develop branch was broken. I added stub methods for missing abstract methods in controllers.

### CODE REVIEW

**Comment by arcuri82** [comment]
Hi

@jgaleotti sorry :( forgot to discuss that current develop is unusable. i did merge into EM by mistake some changes that require an update on EMB. @ZhangMan1126 has been doing that on a branch, but it is not merged yet

**Comment by arcuri82** [comment]
@ZhangMan1126 btw, what is the status on that branch?

**Comment by ZhangMan1126** [comment]
@arcuri82 I checked the updates with evomaster and found some problems. 
the problems are fixed, but need a further check with evomaster.

**Comment by jgaleotti** [comment]
ok, should we discard this PR then?

**Comment by arcuri82** [comment]
@jgaleotti  likely, but let's wait for the other branch first

**Comment by jgaleotti** [comment]
This PR is no longer needed as things were fixed in develop

**Pull request closed without merging**
